src/force-app/main/default/objects/Prix__c/Prix__c.object-meta.xml
<CustomObject>
    <label>Prix</label>
    <nameField>
        <label>Nom de Prix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Prix__c/fields/DelaiDeLivraisonJours__c.field-meta.xml
<CustomField>
    <fullName>DelaiDeLivraisonJours__c</fullName>
    <label>Delai de Livraison jours</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/TransporteurID__c.field-meta.xml
<CustomField>
    <fullName>TransporteurID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Prix</relationshipLabel>
    <relationshipName>Prix</relationshipName>
    <type>Lookup</type>
</CustomField>

src/force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Nom de Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Transporteur__c/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>Livraison transport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/classes/TransporterSelector.cls
public with sharing class TransporterSelector {
    public static List<Prix__c> getTransporteurOrderByPriceDesc(string Pays,string TypeClient) {
        return [
            SELECT Id, TransporteurID__c, DelaiDeLivraisonJours__c,Pays__c,tarif__c,TransporteurID__r.TypeClient__c,TransporteurID__r.name 
            FROM Prix__c  
            where pays__c=:Pays and TransporteurID__r.TypeClient__c LIKE :('%' + TypeClient + '%')
            order by tarif__c asc
            limit 1
            ];
    }

    public static List<Prix__c> getTransporteurOrderByFasterDesc(string Pays,string TypeClient) {
        return [
            SELECT Id, TransporteurID__c, DelaiDeLivraisonJours__c,Pays__c,tarif__c,TransporteurID__r.TypeClient__c,TransporteurID__r.name 
            FROM Prix__c  
            where pays__c=:Pays and TransporteurID__r.TypeClient__c LIKE :('%' + TypeClient + '%')
            order by DelaiDeLivraisonJours__c asc
            limit 1
            ];
    }

    public static void CreateShipping(String Status, String OpportunityId, String shippingOption) {
       
    }



}