src/force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <nameField>
        <label>Nom de Livraison</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Prix__c/Prix__c.object-meta.xml
<CustomObject>
    <label>Prix</label>
    <nameField>
        <label>Nom de Prix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Prix__c/fields/DelaiDeLivraisonJours__c.field-meta.xml
<CustomField>
    <fullName>DelaiDeLivraisonJours__c</fullName>
    <label>Delai de Livraison jours</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/TransporteurID__c.field-meta.xml
<CustomField>
    <fullName>TransporteurID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Prix</relationshipLabel>
    <relationshipName>Prix</relationshipName>
    <type>Lookup</type>
</CustomField>

src/force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Nom de Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/classes/PriceSelectorTest.cls
@IsTest
private class PriceSelectorTest {
    @TestSetup
    static void setup() {
       
        TestDataFactory.createTestgetTransporteurDelai();        
  TestDataFactory.createTestgetTransporteurPrice();
  TestDataFactory.createTestOrders();
    }

    @IsTest
    static void testgetTransporteurOrderByPriceDesc()
    {
        Test.startTest();
        List<Prix__c> results = PriceSelector.getTransporteurOrderByPriceDesc('France','Particulier');
        Test.stopTest();        
        System.assertEquals('best_Price_Transporteur', results[0].TransporteurID__r.name, 'Le transporteur devrait etre best_Price_Transporteur le prix est de '+ results[0].Tarif__c);
    }


    @IsTest
    static void testgetgetTransporteurOrderByFasterDesc()
    {
        Test.startTest();
        List<Prix__c> results = PriceSelector.getTransporteurOrderByFasterDesc('France','Particulier');
        Test.stopTest();        
        System.assertEquals('faster_Transporteur', results[0].TransporteurID__r.name, 'Le transporteur devrait etre faster_Transporteur le delai est de ' + results[0].DelaiDeLivraisonJours__c);
    }


    @IsTest
    static void testgetOtherTransporteur()
    {
        Test.startTest();
        List<Prix__c> results = PriceSelector.getOtherTransporteur('France');
        Test.stopTest();   
        // Validation des résultats
        System.assert(results != null && results.size() > 0, 'Les résultats ne peuvent pas être nuls ou vides');
        
    }

    @IsTest
    static void testCreateShipping()
    {
        List<Order> ord = [SELECT Id FROM Order LIMIT 1  ];
        List<Transporteur__c> transp = [SELECT Id FROM Transporteur__c LIMIT 1  ];
        string transpId=transp[0].Id;
        String ordId=ord[0].Id;
        Test.startTest();
                PriceSelector.CreateShipping('en cours',ordId,'fastest','test Livraison',transpId);                 
        Test.stopTest();
        List<Livraison__c> results = [SELECT Id FROM Livraison__c LIMIT 1  ]; 
        System.assert(results != null && results.size() > 0, 'Les résultats ne peuvent pas être nuls ou vides');
    }

}