src/force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <nameField>
        <label>Nom de Livraison</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Livraison__c/fields/livraisonTransporteur__c.field-meta.xml
<CustomField>
    <fullName>livraisonTransporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>livraisonTransporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

src/force-app/main/default/objects/Livraison__c/fields/OrderLivraison__c.field-meta.xml
<CustomField>
    <fullName>OrderLivraison__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderLivraison</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

src/force-app/main/default/objects/Livraison__c/fields/shippingOption__c.field-meta.xml
<CustomField>
    <fullName>shippingOption__c</fullName>
    <label>shippingOption</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cheapest</fullName>
            </value>
            <value>
                <fullName>fastest</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/force-app/main/default/objects/Livraison__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>livraisons effectuées</fullName>
            </value>
            <value>
                <fullName>en cours</fullName>
            </value>
            <value>
                <fullName>échouées</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/force-app/main/default/objects/Prix__c/Prix__c.object-meta.xml
<CustomObject>
    <label>Prix</label>
    <nameField>
        <label>Nom de Prix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Prix__c/fields/DelaiDeLivraisonJours__c.field-meta.xml
<CustomField>
    <fullName>DelaiDeLivraisonJours__c</fullName>
    <label>Delai de Livraison jours</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <label>Tarif</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/objects/Prix__c/fields/TransporteurID__c.field-meta.xml
<CustomField>
    <fullName>TransporteurID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Prix</relationshipLabel>
    <relationshipName>Prix</relationshipName>
    <type>Lookup</type>
</CustomField>

src/force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Nom de Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/objects/Transporteur__c/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>Livraison transport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/force-app/main/default/classes/PriceSelector.cls
public with sharing class PriceSelector {
  public static List<Prix__c> getTransporteurOrderByPriceAsc(
    string Pays,
    string TypeClient
  ) {
    return [
      SELECT
        Id,
        TransporteurID__c,
        DelaiDeLivraisonJours__c,
        Pays__c,
        tarif__c,
        TransporteurID__r.TypeClient__c,
        TransporteurID__r.name
      FROM Prix__c
      WHERE
        pays__c = :Pays
        AND TransporteurID__r.TypeClient__c =:  TypeClient 
      ORDER BY tarif__c ASC
      LIMIT 1
    ];
  }

  public static List<Prix__c> getTransporteurOrderByFasterAsc(
    string Pays,
    string TypeClient
  ) {
    return [
      SELECT
        Id,
        TransporteurID__c,
        DelaiDeLivraisonJours__c,
        Pays__c,
        tarif__c,
        TransporteurID__r.TypeClient__c,
        TransporteurID__r.name
      FROM Prix__c
      WHERE
        pays__c = :Pays
        AND TransporteurID__r.TypeClient__c  =:  TypeClient 
      ORDER BY DelaiDeLivraisonJours__c ASC
      LIMIT 1
    ];
  }

  public static List<Prix__c> getOtherTransporteur(string Pays) {
    return [
      SELECT
        Id,
        TransporteurID__c,
        DelaiDeLivraisonJours__c,
        Pays__c,
        tarif__c,
        TransporteurID__r.TypeClient__c,
        TransporteurID__r.name
      FROM Prix__c
      WHERE pays__c = :Pays
    ];
  }

  public static void CreateShipping(
    String Status,
    String OrderId,
    String shippingOption,
    string TransporteurName,
    string transporteurid
  ) {
    try {
      System.debug('Status=' + Status);
      System.debug('OrderId=' + OrderId);
      System.debug('shippingOption=' + shippingOption);
      System.debug('TransporteurName=' + TransporteurName);
      Livraison__c newLivraison = new Livraison__c(
        Status__c = Status,
        OrderLivraison__c = OrderId,
        shippingOption__c = shippingOption,
        Name = TransporteurName,
        livraisonTransporteur__c = transporteurid
      );
      insert newLivraison;
      System.debug('Insertion dans Livraison ok');
    } catch (Exception ex) {
      System.debug('Erreur insert ...' + ex.getMessage());
    }
  }
}